### PR TITLE
Deploy d auth check

### PR DESCRIPTION
**Pull request by Hazzard17h**
It was not so easy as i thought. @githubsaturn please review it.

### CODE REVIEW

**Comment by Hazzard17h** [comment]
This resolves also #32

**Comment by Hazzard17h** [comment]
Also resolves #20

**Comment by Hazzard17h** [comment]
Also resolves #31

**Comment by Hazzard17h** [comment]
Also resolves #34

**Comment by Hazzard17h** [comment]
Also resolves #35

**Comment by githubsaturn** [comment]
Thanks @Hazzard17h

**Pull request merged**
