### PR TITLE
Update dependencies 

### PR DESCRIPTION
**Pull request by elribonazo**
After having talked with Caprover team I am proposing a PR to upgrade dependencies to most recent versions.

Something I cannot understand is:
`
chmod +x ./built -R 
`

the -R attribute is supposed to go first, right after the chmod command, but I may be loosing the path here if we are building or using an image that does support that, but afaik, the correct format is after the command not at the end of it.
cc: @githubsaturn 

## Changelog
1. Upgrading dependencies
2. Small code refactor to sync with most recent versions installed
3. Apply code linting & formatting with same rules that were established already.

## PR Checks
- [x] Read the Contribution guidelines
- [x] Communicated with Caprover team by mail
- [x] Reduced changes as much as humanly possible
- [x] Made clean changes
- [ ] My PR is well tested

only thing so far I have not completed is testing but probably community/caprover can help on that?

### CODE REVIEW

**Comment by githubsaturn** [comment]
Changes look good. Can you please fix the build errors so we can merge?

**Comment by elribonazo** [comment]
Yes sorry had not seen, ofc

**Comment by elribonazo** [comment]
I could not reproduce the issue locally... but it not going to happen probably if we upgrade the CI pipelines to use higher versions of nodejs, it was currently used in node 14 and I upgraded to node 20.

**Comment by githubsaturn** [comment]
No it wasn't related to node version. Looks like the problem was that somehow linter and formatter were fighting against each other.

**Pull request merged**
